# Generated by Django 5.1.3 on 2024-11-23 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('episode_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('painting_title', models.CharField(max_length=255)),
                ('youtube_src', models.CharField(max_length=255)),
                ('colors', models.ManyToManyField(to='episodes.color')),
            ],
            options={
                'unique_together': {('season_number', 'episode_number')},
            },
        ),
    ]
