# Generated by Django 5.1.3 on 2024-11-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season_number', 'episode_number']},
        ),
    ]
